import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Motors from './motors'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sipir Tespit Uygulaması</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Motors></Motors>
     
    </div>
  )
}

export default Home
